server:
  port: 8082
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mailtestcjh@gmail.com
    password: xohvhfpztqxdzaqo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB      
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    view-names: th/* 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/SB_CS?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password: 
mybatis:
  type-aliases-package: com.koreaIT.demo.vo
custom:
  siteName: 2023_11_SB_AM
  siteMainUri: http://localhost:8082
  emailFrom: no-reply@localhost
  emailFromName: 2023_11_SB_AM
google:
  client:
    id: 1088460648506-j2nil1cls769igr3kcfu0bnqkn83lvd5.apps.googleusercontent.com
    secret: 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
    redirect-uri: http://localhost:8080/oauth2callback  